version: "3.7"

services:
  pageplug-internal-server:
    image:  harbor.cloud2go.cn/pageplug/pageplug-server:ce-v1.9.20-20230809114200
    environment:
      APPSMITH_REDIS_URL: "redis://redis:6379"
      APPSMITH_MONGODB_URI: "mongodb://mongo:27017/appsmith"
      APPSMITH_ENCRYPTION_PASSWORD: "abcd"
      APPSMITH_ENCRYPTION_SALT: "abcd"
    ports:
      - "8080:8080"
    depends_on:
      - mongo
      - redis
    networks:
      - pageplug
    volumes:
      - ./container-volumes/git-storage:/data/git-storage

  mongo:
    image: mongo:5.0.14
    environment:
      - MONGO_INITDB_DATABASE=appsmith
    volumes:
      - ./container-volumes/mongo:/data/db
    networks:
      - pageplug

  redis:
    image: redis
    networks:
      - pageplug

networks:
  pageplug:
    driver: bridge
